[functions]
  node_bundler="esbuild"
  directory="distnetlify/functions"
  included_files = ["distnetlify/src/**","distnetlify/router.mjs","distnetlify/_virtual/**"]
  external_node_modules = ["react","react-context-slices","express","ua-parser-js","serverless-http","react-dom/server"]

#[dev]
 #command="npm run build"
 #functions="distnetlify/functions"

[[redirects]]
  force = true
  from = "/*"
  status = 200
  to = "/.netlify/functions/app/:splat"
